server:
  port: 8085

spring:
  application:
    name: ai-travel-ai-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.ai.travel.ai: INFO