distributionUrl=https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip
wrapperUrl=https://raw.githubusercontent.com/apache/maven/master/maven-wrapper/src/main/resources/scripts/maven-wrapper.sh
